---
- name: Update apt cache.
  become: yes
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure {{item}} is installed on Debian.
  become: yes  
  apt: "name={{ item }} state=installed"
  with_items: "{{ paquetes }}"
