---
# Include variables and define needed variables.
#- name: Include OS-specific variables.
#  include_vars: "{{ ansible_os_family }}.yml"

# Add-repo if the user aked to do it
- include: add-repo-Debian.yml
  when: ansible_os_family == 'Debian'

- include: add-repo-Fedora-dnf.yml
  when: ansible_distribution == "Fedora" and {{ ansible_distribution_version | version_compare('22', '>=') }}

- include: add-repo-Fedora-yum.yml
  when: ansible_distribution == "Fedora" and {{ ansible_distribution_version | version_compare('22', '<') }}

- include: add-repo-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != "Fedora"

