---
- name: Copy the defult password file
  template:
    src: password.j2
    dest: /tmp/file 

- name: vncserver command
  shell: "sudo -u {{ item.name }} -i vncserver </tmp/file >/tmp/vncpasswd.1 2>/tmp/vncpasswd.2"
  with_items: "{{ vnc_users }}"

- name: Copy the vncservers.conf file in /etc/ directory
  template:
    src: vncservers.conf.j2
    dest: /etc/vncservers.conf
    owner: root
    group: root

- name: Copy the modified "xstartup" file
  template:
    src: xstartup.j2
    dest: "/home/{{ item.name }}/.vnc/xstartup"
    owner: "{{item.name}}"
    mode: 0755
  with_items: "{{ vnc_users }}"

- name: Create a file vncserver in /etc/init.d/ directory
  template:
    src: vncserver.j2
    dest: /etc/init.d/vncserver
    owner: root
    group: root
    mode: 0755
  register: vnc_service

- name: Add vncserver service to default runlevels
  command: "update-rc.d vncserver defaults"
  when: vnc_service.changed

- name: Abrir puertos en firewall-cmd
  firewalld: port="{{ item.vnc_port}}/tcp" permanent=true state=enabled zone=public
  with_items: "{{ vnc_users}}"
  register: puertos_abiertos

- name: Restart the machine#
  become: yes  
  shell: reboot
  async: 60
  poll: 0 
  ignore_errors: true
#  when: puertos_abiertos.changed

#- name: Reiniciar Firewalld
#  shell: "firewall-cmd --reload"
#  register: firewalld_restart 
#  when: puertos_abiertos.changed

#- name: Restart VNC Service
#  ignore_errors: true
#  shell: /etc/init.d/vncserver restart
#  register: vnc_restart
#  when: firewalld_restart.changed

#- name: Restart the machine
#  become: yes  
#  shell: reboot
#  async: 60
#  poll: 0 
#  ignore_errors: true
#  when: vnc_restart.changed
